export const REQUEST_CURRENTUSER_PENDING = "REQUEST_CURRENTUSER_PENDING";

export const REQUEST_CURRENTUSER_SUCCESS = "REQUEST_CURRENTUSER_SUCCESS";

export const REQUEST_CURRENTUSER_FAILED = "REQUEST_CURRENTUSER_FAILED";

export const REQUEST_CATEGORIES_PENDING = "REQUEST_CATEGORIES_PENDING";

export const REQUEST_CATEGORIES_SUCCESS = "REQUEST_CATEGORIES_SUCCESS";

export const REQUEST_CATEGORIES_FAILED = "REQUEST_CATEGORIES_FAILED";

export const SET_CART_ITEMS = 'SET_CART_ITEMS';

export const SET_IS_CART_OPEN = "SET_IS_CART_OPEN";