export const CONSTANTS = {
    REQUEST_CURRENTUSER_PENDING: "REQUEST_CURRENTUSER_PENDING",
    REQUEST_CURRENTUSER_SUCCESS: "REQUEST_CURRENTUSER_SUCCESS",
    REQUEST_CURRENTUSER_FAILED: "REQUEST_CURRENTUSER_FAILED",

    GOOGLE_SIGN_IN_PENDING: "GOOGLE_SIGN_IN_PENDING",
    EMAIL_SIGN_IN_PENDING: "EMAIL_SIGN_IN_PENDING",
    EMAIL_SIGN_UP_PENDING: "EMAIL_SIGN_UP_PENDING",
    REQUEST_SIGN_OUT_PENDING: "REQUEST_SIGN_OUT_PENDING",
    REQUEST_SIGN_OUT_SUCCESS: "REQUEST_SIGN_OUT_SUCCESS",
    REQUEST_SIGN_OUT_FAILED: "REQUEST_SIGN_OUT_FAILED",

    REQUEST_CATEGORIES_PENDING: "REQUEST_CATEGORIES_PENDING",
    REQUEST_CATEGORIES_SUCCESS: "REQUEST_CATEGORIES_SUCCESS",
    REQUEST_CATEGORIES_FAILED: "REQUEST_CATEGORIES_FAILED",

    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_IS_CART_OPEN: "SET_IS_CART_OPEN"
}