export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_CART_ITEMS = 'SET_CART_ITEMS';

export const SET_IS_CART_OPEN = "SET_IS_CART_OPEN";

export const SET_CATEGORIES = "SET_CATEGORIES";